### ISSUE TITLE
C. InsightDescription

### ISSUE THREAD

**Issue by Djmr5** [TC3005B-562-2024/React-Frontend#34]
**Props**

1. priority: string
2. alertId: number - defaults to None, if there is no alertId its not displayed the title
3. icon: <Icon>
4. description: string

**Comment by ArturoCarballo** [comment]
Componente Creado


![imagen_2024-04-18_233241479](https://github.com/TC3005B-562-2024/React-Frontend/assets/102175262/3efabe34-ffee-4bf0-a719-943316be9cdf)

**Comment by ArturoCarballo** [comment]
Esperando revision
